// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// ignore: depend_on_referenced_packages
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2ZyfaS4iO3UCRv-KxZwqU0XJtaMB0cLU',
    appId: '1:926232063538:web:fcc314b9066551d789562b',
    messagingSenderId: '926232063538',
    projectId: 'synapse-92f94',
    authDomain: 'synapse-92f94.firebaseapp.com',
    storageBucket: 'synapse-92f94.appspot.com',
    measurementId: 'G-MX6QWZL7DV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoxrVWhyDAImBe6KfrMoIDXLhxNOIurc4',
    appId: '1:926232063538:android:e03d6dccf59cbf2289562b',
    messagingSenderId: '926232063538',
    projectId: 'synapse-92f94',
    storageBucket: 'synapse-92f94.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtGBYh8O8TkruE8x_hTLuG2alYwbZOhzs',
    appId: '1:926232063538:ios:230f87013f20fb1f89562b',
    messagingSenderId: '926232063538',
    projectId: 'synapse-92f94',
    storageBucket: 'synapse-92f94.appspot.com',
    androidClientId:
        '926232063538-5prji0ust45rmhi24se4fpsjeg0ekirp.apps.googleusercontent.com',
    iosClientId:
        '926232063538-rk9u547nnhp9hb34qivbftk9btvir5ua.apps.googleusercontent.com',
    iosBundleId: 'com.example.synapseTeacher.RunnerTests',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtGBYh8O8TkruE8x_hTLuG2alYwbZOhzs',
    appId: '1:926232063538:ios:230f87013f20fb1f89562b',
    messagingSenderId: '926232063538',
    projectId: 'synapse-92f94',
    storageBucket: 'synapse-92f94.appspot.com',
    androidClientId:
        '926232063538-5prji0ust45rmhi24se4fpsjeg0ekirp.apps.googleusercontent.com',
    iosClientId:
        '926232063538-rk9u547nnhp9hb34qivbftk9btvir5ua.apps.googleusercontent.com',
    iosBundleId: 'com.example.synapseTeacher.RunnerTests',
  );
}
